"""m0_m1_initial_schema

Revision ID: 659b9169a261
Revises: 
Create Date: 2026-09-22 00:49:50.499572
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('key', name=op.f('uq_channels_key'))
    )
    op.create_table('icps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_icps')),
    sa.UniqueConstraint('key', name=op.f('uq_icps_key'))
    )
    op.create_table('market_categories',
    sa.Column('category_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('category_key', name=op.f('pk_market_categories'))
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('generated_date', sa.Date(), nullable=True),
    sa.Column('score_version', sa.String(length=32), nullable=True),
    sa.Column('universe_size', sa.Integer(), nullable=True),
    sa.Column('source_filename', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_snapshots')),
    sa.UniqueConstraint('key', name=op.f('uq_market_snapshots_key')),
    sa.UniqueConstraint('sha256', name=op.f('uq_market_snapshots_sha256'))
    )
    op.create_table('markets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=True),
    sa.Column('iso3', sa.String(length=3), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('is_home_market', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets')),
    sa.UniqueConstraint('iso2', name=op.f('uq_markets_iso2')),
    sa.UniqueConstraint('iso3', name=op.f('uq_markets_iso3')),
    sa.UniqueConstraint('name', name=op.f('uq_markets_name'))
    )
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('ticket_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ticket_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers')),
    sa.UniqueConstraint('key', name=op.f('uq_offers_key'))
    )
    op.create_table('scoring_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normalization_method', sa.Text(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_models')),
    sa.UniqueConstraint('key', 'version', name='uq_scoring_models_key_version')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('used_for', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('source_key', name=op.f('uq_sources_source_key'))
    )
    op.create_table('verticals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('taxonomy_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verticals')),
    sa.UniqueConstraint('key', name=op.f('uq_verticals_key'))
    )
    op.create_table('market_competition_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=64), nullable=False),
    sa.Column('fact_type', sa.String(length=32), nullable=False),
    sa.Column('included_in_score', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_competition_assessments_market_id_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_market_competition_assessments_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_competition_assessments')),
    sa.UniqueConstraint('market_id', 'snapshot_id', name='uq_competition_market_snapshot')
    )
    op.create_table('market_deep_dives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('priority_verticals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority_geographies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_channel', sa.Text(), nullable=True),
    sa.Column('common_buyers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('common_problem_pattern', sa.Text(), nullable=True),
    sa.Column('raw_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_deep_dives_market_id_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_market_deep_dives_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_deep_dives')),
    sa.UniqueConstraint('market_id', 'snapshot_id', name='uq_deep_dive_market_snapshot')
    )
    op.create_table('market_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('metric_key', sa.String(length=128), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('period_label', sa.String(length=64), nullable=False),
    sa.Column('fact_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_observations_market_id_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_market_observations_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_observations')),
    sa.UniqueConstraint('market_id', 'snapshot_id', 'metric_key', 'period_label', name='uq_market_observations_identity')
    )
    op.create_index('ix_market_observations_metric', 'market_observations', ['metric_key'], unique=False)
    op.create_index('ix_market_observations_snapshot_market', 'market_observations', ['snapshot_id', 'market_id'], unique=False)
    op.create_table('market_size_estimates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('fact_type', sa.String(length=32), nullable=False),
    sa.Column('confidence_level', sa.String(length=32), nullable=True),
    sa.Column('tam_min', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('tam_max', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('sam_min', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('sam_max', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('som_accounts_min', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('som_accounts_max', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ticket_min_usd', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ticket_max_usd', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('sam_value_min_usd', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('sam_value_max_usd', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('som_pool_value_min_usd', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('som_pool_value_max_usd', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_size_estimates_market_id_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_market_size_estimates_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_size_estimates')),
    sa.UniqueConstraint('market_id', 'snapshot_id', name='uq_market_size_market_snapshot')
    )
    op.create_table('market_snapshot_categories',
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('category_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['category_key'], ['market_categories.category_key'], name=op.f('fk_market_snapshot_categories_category_key_market_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_snapshot_categories_market_id_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_market_snapshot_categories_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_id', 'snapshot_id', 'category_key', name=op.f('pk_market_snapshot_categories'))
    )
    op.create_table('market_vertical_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('fit_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('coverage', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('tam_min', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('tam_max', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('sam_min', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('sam_max', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ticket_min_usd', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ticket_max_usd', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('priority_geographies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_motion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('problem_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_market_vertical_profiles_confidence_range')),
    sa.CheckConstraint('coverage IS NULL OR (coverage >= 0 AND coverage <= 1)', name=op.f('ck_market_vertical_profiles_coverage_range')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_vertical_profiles_market_id_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_market_vertical_profiles_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_market_vertical_profiles_vertical_id_verticals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_vertical_profiles')),
    sa.UniqueConstraint('market_id', 'vertical_id', 'snapshot_id', name='uq_mvp_market_vertical_snapshot')
    )
    op.create_table('research_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=True),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('icp_id', sa.UUID(), nullable=True),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('metric_key', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('context_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_research_gaps_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['icp_id'], ['icps.id'], name=op.f('fk_research_gaps_icp_id_icps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_research_gaps_market_id_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_research_gaps_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_research_gaps_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_research_gaps_vertical_id_verticals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_gaps')),
    sa.UniqueConstraint('context_fingerprint', name='uq_research_gaps_fingerprint')
    )
    op.create_index('ix_research_gaps_market', 'research_gaps', ['market_id'], unique=False)
    op.create_index('ix_research_gaps_status', 'research_gaps', ['status', 'priority'], unique=False)
    op.create_table('score_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scoring_model_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('universe_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engine_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['scoring_model_id'], ['scoring_models.id'], name=op.f('fk_score_runs_scoring_model_id_scoring_models'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_score_runs_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_runs'))
    )
    op.create_index('ix_score_runs_lookup', 'score_runs', ['snapshot_id', 'scoring_model_id', 'kind'], unique=False)
    op.create_table('scoring_model_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scoring_model_id', sa.UUID(), nullable=False),
    sa.Column('component_key', sa.String(length=128), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('required_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scoring_model_id'], ['scoring_models.id'], name=op.f('fk_scoring_model_components_scoring_model_id_scoring_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_model_components')),
    sa.UniqueConstraint('scoring_model_id', 'component_key', name='uq_model_component_key')
    )
    op.create_table('market_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('score_run_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('coverage', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_market_scores_confidence_range')),
    sa.CheckConstraint('coverage IS NULL OR (coverage >= 0 AND coverage <= 1)', name=op.f('ck_market_scores_coverage_range')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_scores_market_id_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['score_run_id'], ['score_runs.id'], name=op.f('fk_market_scores_score_run_id_score_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_scores')),
    sa.UniqueConstraint('score_run_id', 'market_id', name='uq_market_scores_run_market')
    )
    op.create_table('observation_sources',
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('attribution', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['market_observations.id'], name=op.f('fk_observation_sources_observation_id_market_observations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_observation_sources_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observation_id', 'source_id', name=op.f('pk_observation_sources'))
    )
    op.create_table('market_score_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_score_id', sa.UUID(), nullable=False),
    sa.Column('component_key', sa.String(length=128), nullable=False),
    sa.Column('raw_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('normalized_value', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('weighted_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('coverage', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['market_score_id'], ['market_scores.id'], name=op.f('fk_market_score_components_market_score_id_market_scores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_score_components')),
    sa.UniqueConstraint('market_score_id', 'component_key', name='uq_score_component_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_score_components')
    op.drop_table('observation_sources')
    op.drop_table('market_scores')
    op.drop_table('scoring_model_components')
    op.drop_index('ix_score_runs_lookup', table_name='score_runs')
    op.drop_table('score_runs')
    op.drop_index('ix_research_gaps_status', table_name='research_gaps')
    op.drop_index('ix_research_gaps_market', table_name='research_gaps')
    op.drop_table('research_gaps')
    op.drop_table('market_vertical_profiles')
    op.drop_table('market_snapshot_categories')
    op.drop_table('market_size_estimates')
    op.drop_index('ix_market_observations_snapshot_market', table_name='market_observations')
    op.drop_index('ix_market_observations_metric', table_name='market_observations')
    op.drop_table('market_observations')
    op.drop_table('market_deep_dives')
    op.drop_table('market_competition_assessments')
    op.drop_table('verticals')
    op.drop_table('sources')
    op.drop_table('scoring_models')
    op.drop_table('offers')
    op.drop_table('markets')
    op.drop_table('market_snapshots')
    op.drop_table('market_categories')
    op.drop_table('icps')
    op.drop_table('channels')
    # ### end Alembic commands ###
