"""m0_m1 remediation: availability, temporal provenance, closed vocabularies,
rank-coverage threshold, first-class contextual dimensions, snapshot immutability

Revision ID: 0002_remediation
Revises: 0001_initial
Create Date: 2026-09-22

Hand-written rather than autogenerated: it carries data backfill, CHECK
constraints derived from ``boro_gtm.core.enums.CLOSED_VOCABULARIES`` and two
immutability triggers, none of which Alembic can infer.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0002_remediation"
down_revision = "0001_initial"
branch_labels = None
depends_on = None

# Mirrors boro_gtm.core.enums.CLOSED_VOCABULARIES. Kept literal here so the
# migration is reproducible even if the enums module later evolves; a test
# asserts the two stay in agreement.
FACT_TYPES = ("FACT", "ESTIMATE", "PROXY", "INFERENCE", "HYPOTHESIS")
AVAILABILITY = ("OBSERVED", "NOT_AVAILABLE")
PERIOD_GRANULARITY = ("DATE", "YEAR", "SNAPSHOT", "UNDATED")
ATTRIBUTION = ("EXPLICIT", "METRIC_HINT", "MARKET_LEVEL")
RUN_KINDS = (
    "imported_reference",
    "reference_reproduction",
    "native_recalculation",
    "contextual",
)
RUN_STATUSES = ("PENDING", "RUNNING", "COMPLETED", "FAILED")
GAP_STATUSES = ("OPEN", "IN_PROGRESS", "RESOLVED", "DISMISSED")
GAP_PRIORITIES = ("LOW", "MEDIUM", "HIGH", "CRITICAL")


def _in_list(column: str, values: tuple[str, ...]) -> str:
    rendered = ", ".join(f"'{v}'" for v in values)
    return f"{column} IN ({rendered})"


def upgrade() -> None:
    # ---------------------------------------------------------------
    # Snapshot identity: canonical digest vs literal file bytes (A-5)
    # ---------------------------------------------------------------
    op.add_column(
        "market_snapshots",
        sa.Column("source_file_sha256", sa.String(length=64), nullable=True),
    )

    # ---------------------------------------------------------------
    # Source publication date (provenance, temporal)
    # ---------------------------------------------------------------
    op.add_column("sources", sa.Column("published_at", sa.Date(), nullable=True))

    # ---------------------------------------------------------------
    # Observations: availability + temporal precision
    # ---------------------------------------------------------------
    op.add_column(
        "market_observations",
        sa.Column("period_granularity", sa.String(length=16), nullable=True),
    )
    op.add_column(
        "market_observations", sa.Column("observed_at", sa.Date(), nullable=True)
    )
    op.add_column(
        "market_observations",
        sa.Column("availability", sa.String(length=16), nullable=True),
    )

    # Backfill: "N/D" was previously stored as a fact type. It is an
    # availability statement, so translate it and null the fact type.
    op.execute(
        """
        UPDATE market_observations
           SET availability = CASE
                   WHEN fact_type = 'N/D' OR fact_type IS NULL OR fact_type = 'UNKNOWN'
                        THEN 'NOT_AVAILABLE'
                   ELSE 'OBSERVED'
               END,
               period_granularity = CASE
                   WHEN period_label ~ '^[0-9]{4}$' THEN 'YEAR'
                   WHEN period_label = 'snapshot'   THEN 'SNAPSHOT'
                   ELSE 'UNDATED'
               END
        """
    )
    op.execute(
        """
        UPDATE market_observations
           SET fact_type = NULL, value_numeric = NULL
         WHERE availability = 'NOT_AVAILABLE'
        """
    )

    op.alter_column("market_observations", "period_granularity", nullable=False)
    op.alter_column("market_observations", "availability", nullable=False)
    # Absence of evidence is no longer a fact type, so the column is nullable.
    op.alter_column("market_observations", "fact_type", nullable=True)

    op.create_check_constraint(
        "availability_consistency",
        "market_observations",
        "(availability = 'OBSERVED' AND fact_type IS NOT NULL) OR "
        "(availability = 'NOT_AVAILABLE' AND fact_type IS NULL "
        "AND value_numeric IS NULL)",
    )
    op.create_check_constraint(
        "observed_at_requires_date_granularity",
        "market_observations",
        "(period_granularity = 'DATE' AND observed_at IS NOT NULL) OR "
        "(period_granularity <> 'DATE' AND observed_at IS NULL)",
    )

    # ---------------------------------------------------------------
    # Scoring model: explicit rank-coverage threshold (A-8)
    # ---------------------------------------------------------------
    op.add_column(
        "scoring_models",
        sa.Column(
            "minimum_rank_coverage",
            sa.Numeric(precision=6, scale=4),
            nullable=True,
        ),
    )
    op.execute("UPDATE scoring_models SET minimum_rank_coverage = 0.5")
    op.alter_column("scoring_models", "minimum_rank_coverage", nullable=False)
    op.create_check_constraint(
        "minimum_rank_coverage_range",
        "scoring_models",
        "minimum_rank_coverage >= 0 AND minimum_rank_coverage <= 1",
    )

    # ---------------------------------------------------------------
    # Score runs: first-class contextual dimensions (ADR-014)
    # ---------------------------------------------------------------
    for column, target in (
        ("vertical_id", "verticals"),
        ("icp_id", "icps"),
        ("offer_id", "offers"),
        ("channel_id", "channels"),
    ):
        op.add_column("score_runs", sa.Column(column, sa.UUID(), nullable=True))
        op.create_foreign_key(
            op.f(f"fk_score_runs_{column}_{target}"),
            "score_runs",
            target,
            [column],
            ["id"],
            ondelete="RESTRICT",
        )
    op.add_column(
        "score_runs",
        sa.Column("ticket_usd", sa.Numeric(precision=18, scale=2), nullable=True),
    )
    op.create_index(
        "ix_score_runs_context",
        "score_runs",
        ["vertical_id", "icp_id", "offer_id", "channel_id"],
    )

    # ---------------------------------------------------------------
    # Closed vocabularies (A-2)
    # ---------------------------------------------------------------
    op.create_check_constraint(
        "fact_type_vocabulary",
        "market_observations",
        f"fact_type IS NULL OR {_in_list('fact_type', FACT_TYPES)}",
    )
    op.create_check_constraint(
        "availability_vocabulary",
        "market_observations",
        _in_list("availability", AVAILABILITY),
    )
    op.create_check_constraint(
        "period_granularity_vocabulary",
        "market_observations",
        _in_list("period_granularity", PERIOD_GRANULARITY),
    )

    # Legacy "N/D" on the two assessment tables becomes NULL as well.
    op.alter_column("market_competition_assessments", "fact_type", nullable=True)
    op.alter_column("market_size_estimates", "fact_type", nullable=True)
    op.execute(
        "UPDATE market_competition_assessments SET fact_type = NULL "
        "WHERE fact_type IN ('N/D', 'UNKNOWN')"
    )
    op.execute(
        "UPDATE market_size_estimates SET fact_type = NULL "
        "WHERE fact_type IN ('N/D', 'UNKNOWN')"
    )
    op.create_check_constraint(
        "fact_type_vocabulary",
        "market_competition_assessments",
        f"fact_type IS NULL OR {_in_list('fact_type', FACT_TYPES)}",
    )
    op.create_check_constraint(
        "fact_type_vocabulary",
        "market_size_estimates",
        f"fact_type IS NULL OR {_in_list('fact_type', FACT_TYPES)}",
    )
    op.create_check_constraint(
        "attribution_vocabulary",
        "observation_sources",
        _in_list("attribution", ATTRIBUTION),
    )
    op.create_check_constraint(
        "kind_vocabulary", "score_runs", _in_list("kind", RUN_KINDS)
    )
    op.create_check_constraint(
        "status_vocabulary", "score_runs", _in_list("status", RUN_STATUSES)
    )
    op.create_check_constraint(
        "status_vocabulary", "research_gaps", _in_list("status", GAP_STATUSES)
    )
    op.create_check_constraint(
        "priority_vocabulary", "research_gaps", _in_list("priority", GAP_PRIORITIES)
    )

    # ---------------------------------------------------------------
    # Snapshot / observation immutability (A-6)
    #
    # A deliberately small invariant: block UPDATE on the two evidence tables.
    # INSERT and DELETE are untouched, so imports, cascades, TRUNCATE-based
    # test teardown and `alembic downgrade` all keep working.
    # ---------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION gtm_reject_update() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'relation % is append-only: UPDATE is not permitted', TG_TABLE_NAME
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("market_snapshots", "market_observations"):
        op.execute(
            f"""
            CREATE TRIGGER {table}_no_update
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION gtm_reject_update();
            """
        )


def downgrade() -> None:
    for table in ("market_snapshots", "market_observations"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_update ON {table}")
    op.execute("DROP FUNCTION IF EXISTS gtm_reject_update()")

    op.drop_constraint("ck_research_gaps_priority_vocabulary", "research_gaps")
    op.drop_constraint("ck_research_gaps_status_vocabulary", "research_gaps")
    op.drop_constraint("ck_score_runs_status_vocabulary", "score_runs")
    op.drop_constraint("ck_score_runs_kind_vocabulary", "score_runs")
    op.drop_constraint("ck_observation_sources_attribution_vocabulary", "observation_sources")
    op.drop_constraint("ck_market_size_estimates_fact_type_vocabulary", "market_size_estimates")
    op.drop_constraint(
        "ck_market_competition_assessments_fact_type_vocabulary",
        "market_competition_assessments",
    )
    op.drop_constraint("ck_market_observations_period_granularity_vocabulary", "market_observations")
    op.drop_constraint("ck_market_observations_availability_vocabulary", "market_observations")
    op.drop_constraint("ck_market_observations_fact_type_vocabulary", "market_observations")
    op.drop_constraint(
        "ck_market_observations_observed_at_requires_date_granularity", "market_observations"
    )
    op.drop_constraint("ck_market_observations_availability_consistency", "market_observations")

    op.drop_index("ix_score_runs_context", table_name="score_runs")
    op.drop_column("score_runs", "ticket_usd")
    for column, target in (
        ("vertical_id", "verticals"),
        ("icp_id", "icps"),
        ("offer_id", "offers"),
        ("channel_id", "channels"),
    ):
        op.drop_constraint(op.f(f"fk_score_runs_{column}_{target}"), "score_runs")
        op.drop_column("score_runs", column)

    op.drop_constraint("ck_scoring_models_minimum_rank_coverage_range", "scoring_models")
    op.drop_column("scoring_models", "minimum_rank_coverage")

    op.execute("UPDATE market_observations SET fact_type = 'N/D' WHERE fact_type IS NULL")
    op.alter_column("market_observations", "fact_type", nullable=False)
    op.drop_column("market_observations", "availability")
    op.drop_column("market_observations", "observed_at")
    op.drop_column("market_observations", "period_granularity")

    op.drop_column("sources", "published_at")
    op.drop_column("market_snapshots", "source_file_sha256")
