"""m2_company_discovery

Adds the M2 company-discovery domain: identity anchor, provider evidence,
resolution decisions, claims, derived projections, views, append-only triggers
and the job queue. M0/M1 tables are untouched.

Revision ID: 0003_m2
Revises: 0002_remediation
Create Date: 2026-09-22 19:49:46.862766
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0003_m2'
down_revision = '0002_remediation'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Trigram index supports candidate *retrieval* only; it is never a
    # decision mechanism (design 6.5).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registry_version', sa.String(length=32), nullable=False),
    sa.Column('attribute_key', sa.String(length=128), nullable=False),
    sa.Column('value_kind', sa.String(length=16), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('allowed_units', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_fact_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cardinality', sa.String(length=8), nullable=False),
    sa.Column('projection_strategy', sa.String(length=32), nullable=False),
    sa.Column('conflict_strategy', sa.String(length=32), nullable=False),
    sa.Column('shadow_column', sa.String(length=32), nullable=True),
    sa.Column('value_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_projection', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("cardinality IN ('ONE','MANY')", name=op.f('ck_attribute_definitions_cardinality_vocabulary')),
    sa.CheckConstraint("conflict_strategy IN ('PRECEDENCE','ENVELOPE','FLAG_AMBIGUOUS')", name=op.f('ck_attribute_definitions_conflict_strategy_vocabulary')),
    sa.CheckConstraint("projection_strategy IN ('HIGHEST_PRECEDENCE','ENVELOPE','UNION','LATEST')", name=op.f('ck_attribute_definitions_projection_strategy_vocabulary')),
    sa.CheckConstraint("value_kind IN ('SCALAR','RANGE','SET')", name=op.f('ck_attribute_definitions_value_kind_vocabulary')),
    sa.CheckConstraint("value_type IN ('TEXT','INTEGER','NUMERIC','DATE','BOOLEAN','REFERENCE','DOMAIN','STRUCTURED')", name=op.f('ck_attribute_definitions_value_type_vocabulary')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_definitions')),
    sa.UniqueConstraint('registry_version', 'attribute_key', name='uq_attribute_definition')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('identity_policy_version', sa.String(length=32), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=16), nullable=False),
    sa.Column('merged_into_company_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("(lifecycle_status = 'MERGED') = (merged_into_company_id IS NOT NULL)", name=op.f('ck_companies_merged_requires_survivor')),
    sa.CheckConstraint("lifecycle_status IN ('ACTIVE','MERGED','DISSOLVED')", name=op.f('ck_companies_lifecycle_vocabulary')),
    sa.CheckConstraint('id <> merged_into_company_id', name=op.f('ck_companies_no_self_merge')),
    sa.ForeignKeyConstraint(['merged_into_company_id'], ['companies.id'], name=op.f('fk_companies_merged_into_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index('ix_companies_lifecycle', 'companies', ['lifecycle_status'], unique=False)
    op.create_table('discovery_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED','RUNNING','DONE','FAILED')", name=op.f('ck_discovery_jobs_status_vocabulary')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_jobs'))
    )
    op.create_index('ix_jobs_claimable', 'discovery_jobs', ['status', 'run_after'], unique=False)
    op.create_table('discovery_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('identity_capability', sa.String(length=32), nullable=False),
    sa.Column('key_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_algorithm_version', sa.String(length=32), nullable=True),
    sa.Column('canonicalization_strategy', sa.String(length=64), nullable=False),
    sa.Column('canonicalization_version', sa.String(length=32), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('trust_tier', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("canonicalization_strategy IN ('JSON_CANONICAL_V1','CSV_ROW_V1')", name=op.f('ck_discovery_providers_canonicalization_strategy_vocabulary')),
    sa.CheckConstraint("identity_capability <> 'DERIVED_STABLE_KEY' OR (key_fields IS NOT NULL AND key_algorithm_version IS NOT NULL)", name=op.f('ck_discovery_providers_derived_key_requires_declaration')),
    sa.CheckConstraint("identity_capability IN ('NATIVE_EXTERNAL_ID','DERIVED_STABLE_KEY','CONTENT_ONLY')", name=op.f('ck_discovery_providers_identity_capability_vocabulary')),
    sa.CheckConstraint('trust_tier >= 0 AND trust_tier <= 1', name=op.f('ck_discovery_providers_trust_tier_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_providers')),
    sa.UniqueConstraint('provider_key', name=op.f('uq_discovery_providers_provider_key'))
    )
    op.create_table('projection_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attribute_registry_version', sa.String(length=32), nullable=False),
    sa.Column('identity_policy_version', sa.String(length=32), nullable=False),
    sa.Column('row_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_digests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.Column('scope_company_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projection_runs'))
    )
    op.create_table('company_domains',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('domain_normalized', sa.Text(), nullable=False),
    sa.Column('domain_role', sa.String(length=16), nullable=False),
    sa.Column('derived_from_claim_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.CheckConstraint("domain_role IN ('IDENTITY','ALTERNATE','REDIRECT','COUNTRY_TLD','DEFUNCT','GROUP')", name=op.f('ck_company_domains_domain_role_vocabulary')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_domains_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'domain_normalized', name=op.f('pk_company_domains'))
    )
    op.create_index('ix_company_domains_lookup', 'company_domains', ['domain_normalized'], unique=False)
    op.create_index('uq_identity_domain', 'company_domains', ['domain_normalized'], unique=True, postgresql_where=sa.text("domain_role = 'IDENTITY'"))
    op.create_table('company_locations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('location_type', sa.String(length=32), nullable=False),
    sa.Column('address_normalized', sa.Text(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('address_raw', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('derived_from_claim_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.CheckConstraint("location_type IN ('HEADQUARTERS','BRANCH','DEPOT','REGISTERED_OFFICE')", name=op.f('ck_company_locations_location_type_vocabulary')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_locations_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_company_locations_market_id_markets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('company_id', 'location_type', 'address_normalized', name=op.f('pk_company_locations'))
    )
    op.create_index('ix_company_locations_market', 'company_locations', ['market_id'], unique=False)
    op.create_table('company_market_presences',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('presence_type', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('fact_type', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('derived_from_claim_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.CheckConstraint("presence_type IN ('HEADQUARTERED','BRANCH','OPERATES','SERVES_REMOTELY')", name=op.f('ck_company_market_presences_presence_type_vocabulary')),
    sa.CheckConstraint('effective_to IS NULL OR effective_from < effective_to', name=op.f('ck_company_market_presences_presence_interval_order')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_market_presences_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_company_market_presences_market_id_markets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('company_id', 'market_id', 'presence_type', 'effective_from', name=op.f('pk_company_market_presences'))
    )
    op.create_index('ix_presences_interval', 'company_market_presences', ['effective_from', 'effective_to'], unique=False)
    op.create_index('ix_presences_market', 'company_market_presences', ['market_id', 'presence_type'], unique=False)
    op.create_table('company_names',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name_normalized', sa.Text(), nullable=False),
    sa.Column('name_type', sa.String(length=32), nullable=False),
    sa.Column('name_raw', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('derived_from_claim_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.CheckConstraint("name_type IN ('LEGAL','TRADING','FORMER','LOCALIZED','PROVIDER_DISPLAY')", name=op.f('ck_company_names_name_type_vocabulary')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_names_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'name_normalized', 'name_type', name=op.f('pk_company_names'))
    )
    op.create_index('ix_company_names_trgm', 'company_names', ['name_normalized'], unique=False,
                    postgresql_using='gin', postgresql_ops={'name_normalized': 'gin_trgm_ops'})
    op.create_table('company_profiles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=True),
    sa.Column('primary_domain', sa.Text(), nullable=True),
    sa.Column('legal_form', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('employee_count_min', sa.Integer(), nullable=True),
    sa.Column('employee_count_max', sa.Integer(), nullable=True),
    sa.Column('derived_from_claim_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('projection_conflict', sa.Boolean(), nullable=False),
    sa.Column('attribute_registry_version', sa.String(length=32), nullable=False),
    sa.CheckConstraint('employee_count_min IS NULL OR employee_count_max IS NULL OR employee_count_min <= employee_count_max', name=op.f('ck_company_profiles_employee_envelope_order')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_profiles_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_company_profiles'))
    )
    op.create_table('company_relationships',
    sa.Column('from_company_id', sa.UUID(), nullable=False),
    sa.Column('to_company_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('fact_type', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('derived_from_claim_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.CheckConstraint("relationship_type <> 'SISTER_OF' OR from_company_id < to_company_id", name=op.f('ck_company_relationships_symmetric_canonical_ordering')),
    sa.CheckConstraint("relationship_type IN ('SUBSIDIARY_OF','FRANCHISE_OF','ACQUIRED_BY','SISTER_OF')", name=op.f('ck_company_relationships_relationship_type_vocabulary')),
    sa.CheckConstraint('effective_to IS NULL OR effective_from < effective_to', name=op.f('ck_company_relationships_relationship_interval_order')),
    sa.CheckConstraint('from_company_id <> to_company_id', name=op.f('ck_company_relationships_no_self_relationship')),
    sa.ForeignKeyConstraint(['from_company_id'], ['companies.id'], name=op.f('fk_company_relationships_from_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_company_id'], ['companies.id'], name=op.f('fk_company_relationships_to_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_company_id', 'to_company_id', 'relationship_type', 'effective_from', name=op.f('pk_company_relationships'))
    )
    op.create_index('ix_relationships_interval', 'company_relationships', ['effective_from', 'effective_to'], unique=False)
    op.create_table('company_verticals',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=False),
    sa.Column('classification_method', sa.String(length=32), nullable=False),
    sa.Column('fact_type', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('derived_from_claim_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.CheckConstraint("classification_method IN ('PROVIDER_TAXONOMY','NAICS_MAPPING','KEYWORD_INFERENCE','HUMAN_REVIEW')", name=op.f('ck_company_verticals_classification_method_vocabulary')),
    sa.CheckConstraint("fact_type IS NULL OR fact_type IN ('FACT','ESTIMATE','PROXY','INFERENCE','HYPOTHESIS')", name=op.f('ck_company_verticals_fact_type_vocabulary')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_verticals_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_company_verticals_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('company_id', 'vertical_id', name=op.f('pk_company_verticals'))
    )
    op.create_index('ix_company_verticals_vertical', 'company_verticals', ['vertical_id', 'fact_type'], unique=False)
    op.create_table('discovery_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=True),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('icp_id', sa.UUID(), nullable=True),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('adapter_version', sa.String(length=32), nullable=True),
    sa.Column('allow_partial_resolution', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cost_units', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','FETCHING','PARTIAL_FETCH','FETCHED','NORMALIZING','RESOLVING','COMPLETED','FAILED')", name=op.f('ck_discovery_runs_status_vocabulary')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_discovery_runs_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['icp_id'], ['icps.id'], name=op.f('fk_discovery_runs_icp_id_icps'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_discovery_runs_market_id_markets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['discovery_providers.id'], name=op.f('fk_discovery_runs_provider_id_discovery_providers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_discovery_runs_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_runs'))
    )
    op.create_index('ix_discovery_runs_context', 'discovery_runs', ['market_id', 'vertical_id', 'icp_id', 'channel_id'], unique=False)
    op.create_index('ix_discovery_runs_status', 'discovery_runs', ['status'], unique=False)
    op.create_table('provider_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('provider_external_id', sa.Text(), nullable=False),
    sa.Column('external_id_kind', sa.String(length=16), nullable=False),
    sa.Column('key_algorithm_version', sa.String(length=32), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("external_id_kind <> 'DERIVED' OR key_algorithm_version IS NOT NULL", name=op.f('ck_provider_entities_derived_kind_requires_algorithm_version')),
    sa.CheckConstraint("external_id_kind IN ('NATIVE','DERIVED','CONTENT')", name=op.f('ck_provider_entities_external_id_kind_vocabulary')),
    sa.ForeignKeyConstraint(['provider_id'], ['discovery_providers.id'], name=op.f('fk_provider_entities_provider_id_discovery_providers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_entities')),
    sa.UniqueConstraint('provider_id', 'provider_external_id', name='uq_provider_entity_external_id')
    )
    op.create_table('discovery_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discovery_run_id', sa.UUID(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['discovery_runs.id'], name=op.f('fk_discovery_queries_discovery_run_id_discovery_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_queries')),
    sa.UniqueConstraint('discovery_run_id', 'page_number', name='uq_query_run_page')
    )
    op.create_table('provider_record_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_entity_id', sa.UUID(), nullable=False),
    sa.Column('canonical_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('canonicalization_strategy', sa.String(length=64), nullable=False),
    sa.Column('canonicalization_version', sa.String(length=32), nullable=False),
    sa.Column('parsed_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discovery_query_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("canonicalization_strategy IN ('JSON_CANONICAL_V1','CSV_ROW_V1')", name=op.f('ck_provider_record_versions_canonicalization_strategy_vocabulary')),
    sa.ForeignKeyConstraint(['discovery_query_id'], ['discovery_queries.id'], name=op.f('fk_provider_record_versions_discovery_query_id_discovery_queries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_entity_id'], ['provider_entities.id'], name=op.f('fk_provider_record_versions_provider_entity_id_provider_entities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_record_versions')),
    sa.UniqueConstraint('provider_entity_id', 'canonicalization_strategy', 'canonicalization_version', 'canonical_payload_hash', name='uq_version_identity')
    )
    op.create_index('ix_versions_entity_retrieved', 'provider_record_versions', ['provider_entity_id', 'retrieved_at'], unique=False)
    op.create_index('ix_versions_query', 'provider_record_versions', ['discovery_query_id'], unique=False)
    op.create_table('entity_resolution_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_record_version_id', sa.UUID(), nullable=False),
    sa.Column('candidate_company_id', sa.UUID(), nullable=False),
    sa.Column('match_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 1', name=op.f('ck_entity_resolution_candidates_score_range')),
    sa.ForeignKeyConstraint(['candidate_company_id'], ['companies.id'], name=op.f('fk_entity_resolution_candidates_candidate_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_record_version_id'], ['provider_record_versions.id'], name=op.f('fk_entity_resolution_candidates_provider_record_version_id_provider_record_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_resolution_candidates'))
    )
    op.create_index('ix_candidates_company', 'entity_resolution_candidates', ['candidate_company_id'], unique=False)
    op.create_index('ix_candidates_version', 'entity_resolution_candidates', ['provider_record_version_id'], unique=False)
    op.create_table('entity_resolution_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_entity_id', sa.UUID(), nullable=False),
    sa.Column('provider_record_version_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('merged_company_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('supersedes_decision_id', sa.UUID(), nullable=True),
    sa.Column('identity_policy_version', sa.String(length=32), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(decision IN ('AMBIGUOUS','REJECTED') AND company_id IS NULL) OR (decision NOT IN ('AMBIGUOUS','REJECTED') AND company_id IS NOT NULL)", name=op.f('ck_entity_resolution_decisions_company_required_unless_unresolved')),
    sa.CheckConstraint("(decision IN ('MERGED','SPLIT')) = (merged_company_id IS NOT NULL)", name=op.f('ck_entity_resolution_decisions_merged_company_only_for_merge_split')),
    sa.CheckConstraint("decision IN ('MATCHED','CREATED_NEW','AMBIGUOUS','REJECTED','MERGED','SPLIT')", name=op.f('ck_entity_resolution_decisions_decision_vocabulary')),
    sa.CheckConstraint("method IN ('DETERMINISTIC','CANDIDATE_AUTO','HUMAN_REVIEW')", name=op.f('ck_entity_resolution_decisions_method_vocabulary')),
    sa.CheckConstraint('id <> supersedes_decision_id', name=op.f('ck_entity_resolution_decisions_no_self_supersede')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_entity_resolution_decisions_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merged_company_id'], ['companies.id'], name=op.f('fk_entity_resolution_decisions_merged_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_entity_id'], ['provider_entities.id'], name=op.f('fk_entity_resolution_decisions_provider_entity_id_provider_entities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_record_version_id'], ['provider_record_versions.id'], name=op.f('fk_entity_resolution_decisions_provider_record_version_id_provider_record_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_decision_id', 'provider_entity_id'], ['entity_resolution_decisions.id', 'entity_resolution_decisions.provider_entity_id'], name='fk_supersedes_same_entity'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_resolution_decisions')),
    sa.UniqueConstraint('id', 'provider_entity_id', name='uq_decision_entity')
    )
    op.create_index('ix_decisions_company', 'entity_resolution_decisions', ['company_id'], unique=False)
    op.create_index('ix_decisions_entity_decided', 'entity_resolution_decisions', ['provider_entity_id', 'decided_at'], unique=False)
    op.create_index('ix_decisions_ambiguous', 'entity_resolution_decisions', ['decided_at'], unique=False, postgresql_where=sa.text("decision = 'AMBIGUOUS'"))
    op.create_index('uq_resolution_root', 'entity_resolution_decisions', ['provider_entity_id'], unique=True, postgresql_where=sa.text('supersedes_decision_id IS NULL'))
    op.create_index('uq_resolution_supersedes', 'entity_resolution_decisions', ['supersedes_decision_id'], unique=True, postgresql_where=sa.text('supersedes_decision_id IS NOT NULL'))
    op.create_table('provider_record_bodies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_record_version_id', sa.UUID(), nullable=False),
    sa.Column('raw_body', sa.LargeBinary(), nullable=False),
    sa.Column('raw_body_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discovery_query_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['discovery_query_id'], ['discovery_queries.id'], name=op.f('fk_provider_record_bodies_discovery_query_id_discovery_queries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_record_version_id'], ['provider_record_versions.id'], name=op.f('fk_provider_record_bodies_provider_record_version_id_provider_record_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_record_bodies')),
    sa.UniqueConstraint('provider_record_version_id', 'raw_body_sha256', name='uq_body_version_digest')
    )
    op.create_index('ix_bodies_version_retrieved', 'provider_record_bodies', ['provider_record_version_id', 'retrieved_at'], unique=False)
    op.create_table('provider_record_normalizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_record_version_id', sa.UUID(), nullable=False),
    sa.Column('normalizer_version', sa.String(length=32), nullable=False),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_record_version_id'], ['provider_record_versions.id'], name=op.f('fk_provider_record_normalizations_provider_record_version_id_provider_record_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_record_normalizations')),
    sa.UniqueConstraint('provider_record_version_id', 'normalizer_version', name='uq_normalization_version')
    )
    op.create_table('provider_record_sightings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_record_version_id', sa.UUID(), nullable=False),
    sa.Column('discovery_query_id', sa.UUID(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discovery_query_id'], ['discovery_queries.id'], name=op.f('fk_provider_record_sightings_discovery_query_id_discovery_queries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_record_version_id'], ['provider_record_versions.id'], name=op.f('fk_provider_record_sightings_provider_record_version_id_provider_record_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_record_sightings')),
    sa.UniqueConstraint('provider_record_version_id', 'discovery_query_id', name='uq_sighting_version_query')
    )
    op.create_table('company_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attribute_key', sa.String(length=128), nullable=False),
    sa.Column('attribute_registry_version', sa.String(length=32), nullable=False),
    sa.Column('value_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_numeric', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_ref_id', sa.UUID(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('fact_type', sa.String(length=32), nullable=True),
    sa.Column('availability', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('provider_record_version_id', sa.UUID(), nullable=True),
    sa.Column('subject_company_id', sa.UUID(), nullable=True),
    sa.Column('resolution_decision_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.Date(), nullable=True),
    sa.Column('period_granularity', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(availability = 'OBSERVED' AND fact_type IS NOT NULL) OR (availability = 'NOT_AVAILABLE' AND fact_type IS NULL  AND value_jsonb IS NULL AND value_numeric IS NULL  AND value_text IS NULL AND value_ref_id IS NULL)", name=op.f('ck_company_claims_availability_consistency')),
    sa.CheckConstraint("(period_granularity = 'DATE' AND observed_at IS NOT NULL) OR (period_granularity <> 'DATE' AND observed_at IS NULL)", name=op.f('ck_company_claims_observed_at_requires_date_granularity')),
    sa.CheckConstraint("availability IN ('OBSERVED','NOT_AVAILABLE')", name=op.f('ck_company_claims_availability_vocabulary')),
    sa.CheckConstraint("fact_type IS NULL OR fact_type IN ('FACT','ESTIMATE','PROXY','INFERENCE','HYPOTHESIS')", name=op.f('ck_company_claims_fact_type_vocabulary')),
    sa.CheckConstraint("period_granularity IN ('DATE','YEAR','SNAPSHOT','UNDATED')", name=op.f('ck_company_claims_period_granularity_vocabulary')),
    sa.CheckConstraint('(provider_record_version_id IS NOT NULL) <> (subject_company_id IS NOT NULL)', name=op.f('ck_company_claims_exactly_one_attribution_path')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_company_claims_confidence_range')),
    sa.ForeignKeyConstraint(['provider_record_version_id'], ['provider_record_versions.id'], name=op.f('fk_company_claims_provider_record_version_id_provider_record_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolution_decision_id'], ['entity_resolution_decisions.id'], name=op.f('fk_company_claims_resolution_decision_id_entity_resolution_decisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_company_id'], ['companies.id'], name=op.f('fk_company_claims_subject_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_claims'))
    )
    op.create_index('ix_claims_attribute', 'company_claims', ['attribute_key', 'observed_at'], unique=False)
    op.create_index('ix_claims_subject', 'company_claims', ['subject_company_id'], unique=False)
    op.create_index('ix_claims_version', 'company_claims', ['provider_record_version_id'], unique=False)
    op.create_table('company_relationship_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_company_id', sa.UUID(), nullable=False),
    sa.Column('to_company_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('assertion', sa.String(length=16), nullable=False),
    sa.Column('supersedes_claim_id', sa.UUID(), nullable=True),
    sa.Column('provider_record_version_id', sa.UUID(), nullable=True),
    sa.Column('resolution_decision_id', sa.UUID(), nullable=True),
    sa.Column('fact_type', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('observed_at', sa.Date(), nullable=True),
    sa.Column('period_granularity', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("assertion IN ('ASSERTED','RETRACTED')", name=op.f('ck_company_relationship_claims_assertion_vocabulary')),
    sa.CheckConstraint("relationship_type <> 'SISTER_OF' OR from_company_id < to_company_id", name=op.f('ck_company_relationship_claims_symmetric_canonical_ordering')),
    sa.CheckConstraint("relationship_type IN ('SUBSIDIARY_OF','FRANCHISE_OF','ACQUIRED_BY','SISTER_OF')", name=op.f('ck_company_relationship_claims_relationship_type_vocabulary')),
    sa.CheckConstraint('from_company_id <> to_company_id', name=op.f('ck_company_relationship_claims_no_self_relationship')),
    sa.CheckConstraint('id <> supersedes_claim_id', name=op.f('ck_company_relationship_claims_no_self_supersede')),
    sa.CheckConstraint('valid_from IS NULL OR valid_to IS NULL OR valid_from < valid_to', name=op.f('ck_company_relationship_claims_valid_interval')),
    sa.ForeignKeyConstraint(['from_company_id'], ['companies.id'], name=op.f('fk_company_relationship_claims_from_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_record_version_id'], ['provider_record_versions.id'], name=op.f('fk_company_relationship_claims_provider_record_version_id_provider_record_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolution_decision_id'], ['entity_resolution_decisions.id'], name=op.f('fk_company_relationship_claims_resolution_decision_id_entity_resolution_decisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_claim_id'], ['company_relationship_claims.id'], name=op.f('fk_company_relationship_claims_supersedes_claim_id_company_relationship_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_company_id'], ['companies.id'], name=op.f('fk_company_relationship_claims_to_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_relationship_claims')),
    sa.UniqueConstraint('supersedes_claim_id', name='uq_relationship_supersedes')
    )
    op.create_index('ix_relationship_claims_from', 'company_relationship_claims', ['from_company_id', 'relationship_type'], unique=False)
    op.create_index('ix_relationship_claims_to', 'company_relationship_claims', ['to_company_id', 'relationship_type'], unique=False)
    op.create_table('entity_resolution_heads',
    sa.Column('provider_entity_id', sa.UUID(), nullable=False),
    sa.Column('current_decision_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_entity_resolution_heads_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_decision_id'], ['entity_resolution_decisions.id'], name=op.f('fk_entity_resolution_heads_current_decision_id_entity_resolution_decisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_entity_id'], ['provider_entities.id'], name=op.f('fk_entity_resolution_heads_provider_entity_id_provider_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_entity_id', name=op.f('pk_entity_resolution_heads'))
    )

    # ------------------------------------------------------------------
    # Append-only evidence: reuse the M0 rejection trigger (ADR-018).
    # INSERT and DELETE stay permitted so cascades, retention pruning and
    # TRUNCATE-based test teardown all keep working.
    # ------------------------------------------------------------------
    for table in (
        "provider_entities",
        "provider_record_versions",
        "provider_record_bodies",
        "provider_record_normalizations",
        "provider_record_sightings",
        "discovery_queries",
        "entity_resolution_candidates",
        "entity_resolution_decisions",
        "company_claims",
        "company_relationship_claims",
    ):
        op.execute(
            f"""
            CREATE TRIGGER {table}_no_update
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION gtm_reject_update();
            """
        )

    # ------------------------------------------------------------------
    # Views. Everything time-varying lives here, never in a projection.
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE VIEW current_entity_resolutions AS
        SELECT d.*
        FROM entity_resolution_decisions d
        WHERE NOT EXISTS (
            SELECT 1 FROM entity_resolution_decisions s
            WHERE s.supersedes_decision_id = d.id
        );
        """
    )
    op.execute(
        """
        CREATE VIEW current_company_relationships AS
        SELECT * FROM company_relationships
        WHERE (effective_from <= CURRENT_DATE)
          AND (effective_to IS NULL OR effective_to > CURRENT_DATE);
        """
    )
    op.execute(
        """
        CREATE VIEW current_company_market_presences AS
        SELECT * FROM company_market_presences
        WHERE (effective_from <= CURRENT_DATE)
          AND (effective_to IS NULL OR effective_to > CURRENT_DATE);
        """
    )
    op.execute(
        """
        CREATE VIEW company_relationships_bidirectional AS
        SELECT from_company_id AS company_id,
               to_company_id   AS related_company_id,
               relationship_type,
               'CANONICAL'     AS direction,
               effective_from, effective_to
        FROM company_relationships
        UNION ALL
        SELECT to_company_id, from_company_id,
               CASE relationship_type
                    WHEN 'SUBSIDIARY_OF' THEN 'PARENT_OF'
                    WHEN 'FRANCHISE_OF'  THEN 'FRANCHISOR_OF'
                    WHEN 'ACQUIRED_BY'   THEN 'ACQUIRER_OF'
                    WHEN 'SISTER_OF'     THEN 'SISTER_OF'
               END,
               'DERIVED', effective_from, effective_to
        FROM company_relationships;
        """
    )
    op.execute(
        """
        CREATE VIEW company_claims_effective AS
        SELECT c.*, h.company_id AS effective_company_id
        FROM company_claims c
        JOIN provider_record_versions v ON v.id = c.provider_record_version_id
        JOIN entity_resolution_heads  h ON h.provider_entity_id = v.provider_entity_id
        WHERE h.company_id IS NOT NULL
        UNION ALL
        SELECT c.*, c.subject_company_id AS effective_company_id
        FROM company_claims c
        WHERE c.subject_company_id IS NOT NULL;
        """
    )
    # ### end hand-written M2 objects ###


def downgrade() -> None:
    for view in (
        "company_claims_effective",
        "company_relationships_bidirectional",
        "current_company_market_presences",
        "current_company_relationships",
        "current_entity_resolutions",
    ):
        op.execute(f"DROP VIEW IF EXISTS {view}")
    for table in (
        "company_relationship_claims",
        "company_claims",
        "entity_resolution_decisions",
        "entity_resolution_candidates",
        "discovery_queries",
        "provider_record_sightings",
        "provider_record_normalizations",
        "provider_record_bodies",
        "provider_record_versions",
        "provider_entities",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_update ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_resolution_heads')
    op.drop_index('ix_relationship_claims_to', table_name='company_relationship_claims')
    op.drop_index('ix_relationship_claims_from', table_name='company_relationship_claims')
    op.drop_table('company_relationship_claims')
    op.drop_index('ix_claims_version', table_name='company_claims')
    op.drop_index('ix_claims_subject', table_name='company_claims')
    op.drop_index('ix_claims_attribute', table_name='company_claims')
    op.drop_table('company_claims')
    op.drop_table('provider_record_sightings')
    op.drop_table('provider_record_normalizations')
    op.drop_index('ix_bodies_version_retrieved', table_name='provider_record_bodies')
    op.drop_table('provider_record_bodies')
    op.drop_index('ix_decisions_entity_decided', table_name='entity_resolution_decisions')
    op.drop_index('uq_resolution_supersedes', table_name='entity_resolution_decisions', postgresql_where=sa.text('supersedes_decision_id IS NOT NULL'))
    op.drop_index('uq_resolution_root', table_name='entity_resolution_decisions', postgresql_where=sa.text('supersedes_decision_id IS NULL'))
    op.drop_index('ix_decisions_ambiguous', table_name='entity_resolution_decisions', postgresql_where=sa.text("decision = 'AMBIGUOUS'"))
    op.drop_index('ix_decisions_company', table_name='entity_resolution_decisions')
    op.drop_table('entity_resolution_decisions')
    op.drop_index('ix_candidates_version', table_name='entity_resolution_candidates')
    op.drop_index('ix_candidates_company', table_name='entity_resolution_candidates')
    op.drop_table('entity_resolution_candidates')
    op.drop_index('ix_versions_query', table_name='provider_record_versions')
    op.drop_index('ix_versions_entity_retrieved', table_name='provider_record_versions')
    op.drop_table('provider_record_versions')
    op.drop_table('discovery_queries')
    op.drop_index('ix_provider_entities_collision', table_name='provider_entities')
    op.drop_table('provider_entities')
    op.drop_index('ix_discovery_runs_status', table_name='discovery_runs')
    op.drop_index('ix_discovery_runs_context', table_name='discovery_runs')
    op.drop_table('discovery_runs')
    op.drop_index('ix_company_verticals_vertical', table_name='company_verticals')
    op.drop_table('company_verticals')
    op.drop_index('ix_relationships_interval', table_name='company_relationships')
    op.drop_table('company_relationships')
    op.drop_table('company_profiles')
    op.drop_index('ix_company_names_trgm', table_name='company_names')
    op.drop_table('company_names')
    op.drop_index('ix_presences_market', table_name='company_market_presences')
    op.drop_index('ix_presences_interval', table_name='company_market_presences')
    op.drop_table('company_market_presences')
    op.drop_index('ix_company_locations_market', table_name='company_locations')
    op.drop_table('company_locations')
    op.drop_index('uq_identity_domain', table_name='company_domains', postgresql_where=sa.text("domain_role = 'IDENTITY'"))
    op.drop_index('ix_company_domains_lookup', table_name='company_domains')
    op.drop_table('company_domains')
    op.drop_table('projection_runs')
    op.drop_table('discovery_providers')
    op.drop_index('ix_jobs_claimable', table_name='discovery_jobs')
    op.drop_table('discovery_jobs')
    op.drop_index('ix_companies_lifecycle', table_name='companies')
    op.drop_table('companies')
    op.drop_table('attribute_definitions')
    # ### end Alembic commands ###
