"""m3_operational_research

Revision ID: 0004_m3
Revises: 0003_m2
Create Date: 2026-09-25 15:42:24.872129
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0004_m3'
down_revision = '0003_m2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_artifact_bodies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_body_sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_body', sa.LargeBinary(), nullable=True),
    sa.Column('byte_length', sa.Integer(), nullable=False),
    sa.Column('body_retention', sa.String(length=16), nullable=False),
    sa.Column('pruned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("body_retention IN ('RETAINED','PRUNED')", name=op.f('ck_research_artifact_bodies_ck_body_retention_vocabulary')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_artifact_bodies')),
    sa.UniqueConstraint('raw_body_sha256', name='uq_body_sha256')
    )
    op.create_index('ix_bodies_retained', 'research_artifact_bodies', ['body_retention'], unique=False)
    op.create_table('research_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonicalization_strategy', sa.String(length=32), nullable=False),
    sa.Column('canonicalization_version', sa.String(length=16), nullable=False),
    sa.Column('canonical_content_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("canonicalization_strategy IN ('HTML_TEXT_V1','PDF_TEXT_V1','JSON_CANONICAL_V1','PLAINTEXT_V1')", name=op.f('ck_research_artifacts_ck_artifact_strategy_vocabulary')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_artifacts')),
    sa.UniqueConstraint('canonicalization_strategy', 'canonicalization_version', 'canonical_content_hash', name='uq_artifact_identity')
    )
    op.create_table('research_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('normalized_locator', sa.Text(), nullable=False),
    sa.Column('locator_policy_version', sa.String(length=16), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('registrable_domain', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sources')),
    sa.UniqueConstraint('normalized_locator', 'locator_policy_version', name='uq_source_locator')
    )
    op.create_index('ix_sources_registrable_domain', 'research_sources', ['registrable_domain'], unique=False)
    op.create_table('identity_review_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('signal_kind', sa.String(length=32), nullable=False),
    sa.Column('normalized_concern', sa.Text(), nullable=False),
    sa.Column('signal_policy_version', sa.String(length=16), nullable=False),
    sa.Column('signal_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('first_raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("signal_kind IN ('POSSIBLE_DUPLICATE','POSSIBLE_PARENT','POSSIBLE_ACQUISITION','DOMAIN_MISMATCH','NAME_MISMATCH','POSSIBLE_CEASED_TRADING')", name=op.f('ck_identity_review_signals_ck_signal_kind_vocabulary')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_identity_review_signals_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], name=op.f('fk_identity_review_signals_related_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_review_signals')),
    sa.UniqueConstraint('signal_fingerprint', name='uq_signal_fingerprint')
    )
    op.create_index('ix_signals_company_kind', 'identity_review_signals', ['company_id', 'signal_kind'], unique=False)
    op.create_table('operational_research_profiles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contradictions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('corroborating_publisher_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('derived_from_claim_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('assertion_policy_version', sa.String(length=16), nullable=False),
    sa.Column('publisher_policy_version', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_operational_research_profiles_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_operational_research_profiles'))
    )
    op.create_table('operational_research_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('research_policy_version', sa.String(length=32), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('target_attribute_keys', sa.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('plan_inputs', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('research_plan_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_operational_research_runs_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_operational_research_runs_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_research_runs')),
    sa.UniqueConstraint('research_plan_hash', name='uq_run_plan_hash')
    )
    op.create_index('ix_research_runs_company', 'operational_research_runs', ['company_id'], unique=False)
    op.create_table('research_artifact_derivations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('body_id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('canonicalization_strategy', sa.String(length=32), nullable=False),
    sa.Column('canonicalization_version', sa.String(length=16), nullable=False),
    sa.Column('canonical_content_hash', sa.String(length=64), nullable=False),
    sa.Column('derivation_status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source_published_at', sa.Date(), nullable=True),
    sa.Column('source_published_granularity', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('derived_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(source_published_at IS NOT NULL) = (source_published_granularity <> 'UNDATED')", name=op.f('ck_research_artifact_derivations_ck_derivation_published_consistency')),
    sa.CheckConstraint("canonicalization_strategy IN ('HTML_TEXT_V1','PDF_TEXT_V1','JSON_CANONICAL_V1','PLAINTEXT_V1')", name=op.f('ck_research_artifact_derivations_ck_derivation_strategy_vocabulary')),
    sa.CheckConstraint("derivation_status IN ('OK','FAILED')", name=op.f('ck_research_artifact_derivations_ck_derivation_status_vocabulary')),
    sa.CheckConstraint("source_published_granularity IN ('DATE','MONTH','YEAR','UNDATED')", name=op.f('ck_research_artifact_derivations_ck_derivation_granularity_vocabulary')),
    sa.ForeignKeyConstraint(['artifact_id'], ['research_artifacts.id'], name=op.f('fk_research_artifact_derivations_artifact_id_research_artifacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['body_id'], ['research_artifact_bodies.id'], name=op.f('fk_research_artifact_derivations_body_id_research_artifact_bodies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_artifact_derivations')),
    sa.UniqueConstraint('body_id', 'canonicalization_strategy', 'canonicalization_version', name='uq_derivation_contract'),
    sa.UniqueConstraint('id', 'body_id', name='uq_derivation_body')
    )
    op.create_index('ix_derivations_artifact', 'research_artifact_derivations', ['artifact_id'], unique=False)
    op.create_table('research_body_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('body_id', sa.UUID(), nullable=False),
    sa.Column('classifier_policy_version', sa.String(length=16), nullable=False),
    sa.Column('sniffed_media_type', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('encoding', sa.String(length=32), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['research_artifact_bodies.id'], name=op.f('fk_research_body_classifications_body_id_research_artifact_bodies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_body_classifications')),
    sa.UniqueConstraint('body_id', 'classifier_policy_version', name='uq_body_classification')
    )
    op.create_table('research_text_derivations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('body_id', sa.UUID(), nullable=False),
    sa.Column('text_extraction_policy_version', sa.String(length=16), nullable=False),
    sa.Column('redaction_policy_version', sa.String(length=16), nullable=False),
    sa.Column('text_derivation_contract_hash', sa.String(length=64), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('page_offsets', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('text_retention', sa.String(length=16), nullable=False),
    sa.Column('pruned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('derived_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("text_retention IN ('RETAINED','PRUNED')", name=op.f('ck_research_text_derivations_ck_text_retention_vocabulary')),
    sa.ForeignKeyConstraint(['body_id'], ['research_artifact_bodies.id'], name=op.f('fk_research_text_derivations_body_id_research_artifact_bodies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_text_derivations')),
    sa.UniqueConstraint('body_id', 'text_derivation_contract_hash', name='uq_text_derivation_contract'),
    sa.UniqueConstraint('id', 'body_id', name='uq_text_derivation_body')
    )
    op.create_table('operational_research_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('failure_stage', sa.String(length=16), nullable=True),
    sa.Column('allow_partial_assertion', sa.Boolean(), nullable=False),
    sa.Column('cost_units', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('attempt_seed_inputs', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('attempt_seed_inputs_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovery_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','DISCOVERING','FETCHING','EXTRACTING','ASSERTING','COMPLETED','PARTIAL','FAILED')", name=op.f('ck_operational_research_attempts_ck_attempt_status_vocabulary')),
    sa.ForeignKeyConstraint(['run_id'], ['operational_research_runs.id'], name=op.f('fk_operational_research_attempts_run_id_operational_research_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_research_attempts')),
    sa.UniqueConstraint('run_id', 'attempt_number', name='uq_attempt_number')
    )
    op.create_index('ix_attempts_status', 'operational_research_attempts', ['status'], unique=False)
    op.create_index('uq_attempt_live', 'operational_research_attempts', ['run_id'], unique=True, postgresql_where="status NOT IN ('COMPLETED','PARTIAL','FAILED')")
    op.create_table('operational_research_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('attribute_key', sa.String(length=128), nullable=False),
    sa.Column('gap_kind', sa.String(length=32), nullable=False),
    sa.Column('first_raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("gap_kind IN ('NO_EVIDENCE','INSUFFICIENT_EVIDENCE','STALE_EVIDENCE','CONTRADICTED','UNRESOLVABLE_SOURCE','NO_CRAWLABLE_SEED')", name=op.f('ck_operational_research_gaps_ck_gap_kind_vocabulary')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_operational_research_gaps_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['operational_research_runs.id'], name=op.f('fk_operational_research_gaps_run_id_operational_research_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_research_gaps')),
    sa.UniqueConstraint('run_id', 'attribute_key', 'gap_kind', name='uq_gap_identity')
    )
    op.create_index('ix_gaps_company_kind', 'operational_research_gaps', ['company_id', 'gap_kind'], unique=False)
    op.create_table('operational_research_plan_profiles',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('coverage', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('confidence_summary', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('contradiction_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('required_attribute_count', sa.Integer(), nullable=False),
    sa.Column('covered_attribute_count', sa.Integer(), nullable=False),
    sa.Column('not_applicable_attribute_count', sa.Integer(), nullable=False),
    sa.Column('open_gap_count', sa.Integer(), nullable=False),
    sa.Column('assertion_policy_version', sa.String(length=16), nullable=False),
    sa.Column('publisher_policy_version', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_operational_research_plan_profiles_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['operational_research_runs.id'], name=op.f('fk_operational_research_plan_profiles_run_id_operational_research_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_operational_research_plan_profiles'))
    )
    op.create_table('research_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text_derivation_id', sa.UUID(), nullable=False),
    sa.Column('body_id', sa.UUID(), nullable=False),
    sa.Column('extractor_kind', sa.String(length=16), nullable=False),
    sa.Column('extractor_id', sa.String(length=128), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_template_version', sa.String(length=32), nullable=True),
    sa.Column('output_schema_version', sa.String(length=32), nullable=False),
    sa.Column('determinism', sa.String(length=16), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sample_execution_id', sa.String(length=64), nullable=True),
    sa.Column('extraction_contract_hash', sa.String(length=64), nullable=False),
    sa.Column('extractor_confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('observations', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('raw_output_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("determinism = 'DETERMINISTIC' OR sample_execution_id IS NOT NULL", name=op.f('ck_research_extractions_ck_sampled_requires_execution_slot')),
    sa.CheckConstraint("determinism IN ('DETERMINISTIC','SAMPLED')", name=op.f('ck_research_extractions_ck_extraction_determinism_vocabulary')),
    sa.CheckConstraint("extractor_kind IN ('RULE','PARSER','MODEL','HUMAN')", name=op.f('ck_research_extractions_ck_extractor_kind_vocabulary')),
    sa.ForeignKeyConstraint(['body_id'], ['research_artifact_bodies.id'], name=op.f('fk_research_extractions_body_id_research_artifact_bodies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['text_derivation_id', 'body_id'], ['research_text_derivations.id', 'research_text_derivations.body_id'], name='fk_extraction_same_body'),
    sa.ForeignKeyConstraint(['text_derivation_id'], ['research_text_derivations.id'], name=op.f('fk_research_extractions_text_derivation_id_research_text_derivations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_extractions')),
    sa.UniqueConstraint('id', 'body_id', name='uq_extraction_body')
    )
    op.create_index('uq_extraction_contract', 'research_extractions', ['text_derivation_id', 'extraction_contract_hash', 'sample_execution_id'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('identity_review_signal_occurrences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('occurrence_number', sa.Integer(), nullable=False),
    sa.Column('raised_by_attempt_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_occurrence_id', sa.UUID(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raised_by_attempt_id'], ['operational_research_attempts.id'], name=op.f('fk_identity_review_signal_occurrences_raised_by_attempt_id_operational_research_attempts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['signal_id'], ['identity_review_signals.id'], name=op.f('fk_identity_review_signal_occurrences_signal_id_identity_review_signals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_occurrence_id'], ['identity_review_signal_occurrences.id'], name=op.f('fk_identity_review_signal_occurrences_supersedes_occurrence_id_identity_review_signal_occurrences'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_review_signal_occurrences')),
    sa.UniqueConstraint('signal_id', 'occurrence_number', name='uq_occurrence_number')
    )
    op.create_index('ix_occurrence_attempt', 'identity_review_signal_occurrences', ['raised_by_attempt_id'], unique=False)
    op.create_index('uq_occurrence_open', 'identity_review_signal_occurrences', ['signal_id'], unique=True, postgresql_where='is_open')
    op.create_table('research_attempt_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('extraction_id', sa.UUID(), nullable=False),
    sa.Column('usage_role', sa.String(length=16), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("usage_role IN ('CREATED','REUSED')", name=op.f('ck_research_attempt_extractions_ck_usage_role_vocabulary')),
    sa.ForeignKeyConstraint(['attempt_id'], ['operational_research_attempts.id'], name=op.f('fk_research_attempt_extractions_attempt_id_operational_research_attempts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['extraction_id'], ['research_extractions.id'], name=op.f('fk_research_attempt_extractions_extraction_id_research_extractions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_attempt_extractions')),
    sa.UniqueConstraint('attempt_id', 'extraction_id', name='uq_attempt_extraction')
    )
    op.create_index('ix_attempt_extraction_extraction', 'research_attempt_extractions', ['extraction_id'], unique=False)
    op.create_table('research_fetch_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('body_id', sa.UUID(), nullable=True),
    sa.Column('fetch_outcome', sa.String(length=20), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('declared_content_type', sa.String(length=128), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=64), nullable=True),
    sa.Column('validated_by', sa.String(length=16), nullable=True),
    sa.Column('validator_value', sa.String(length=255), nullable=True),
    sa.Column('request_headers_digest', sa.String(length=64), nullable=True),
    sa.Column('error_class', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(fetch_outcome = 'OK' AND body_id IS NOT NULL) OR (fetch_outcome = 'NOT_MODIFIED' AND body_id IS NOT NULL    AND http_status = 304 AND validated_by IS NOT NULL) OR (fetch_outcome NOT IN ('OK','NOT_MODIFIED') AND body_id IS NULL)", name=op.f('ck_research_fetch_events_ck_fetch_body_semantics')),
    sa.CheckConstraint("fetch_outcome IN ('OK','NOT_MODIFIED','NOT_FOUND','GONE','DENIED','LOGIN_WALL','TIMEOUT','ROBOTS_DENIED','TOO_LARGE','MIME_MISMATCH','TRANSPORT_ERROR')", name=op.f('ck_research_fetch_events_ck_fetch_outcome_vocabulary')),
    sa.CheckConstraint("validated_by IS NULL OR validated_by IN ('ETAG','LAST_MODIFIED')", name=op.f('ck_research_fetch_events_ck_fetch_validator_vocabulary')),
    sa.ForeignKeyConstraint(['attempt_id'], ['operational_research_attempts.id'], name=op.f('fk_research_fetch_events_attempt_id_operational_research_attempts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['body_id'], ['research_artifact_bodies.id'], name=op.f('fk_research_fetch_events_body_id_research_artifact_bodies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], name=op.f('fk_research_fetch_events_source_id_research_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_fetch_events')),
    sa.UniqueConstraint('id', 'body_id', name='uq_fetch_event_body')
    )
    op.create_index('ix_fetch_attempt', 'research_fetch_events', ['attempt_id'], unique=False)
    op.create_index('ix_fetch_body', 'research_fetch_events', ['body_id'], unique=False)
    op.create_index('ix_fetch_source_time', 'research_fetch_events', ['source_id', 'retrieved_at'], unique=False)
    op.create_table('research_source_discoveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('discovery_method', sa.String(length=16), nullable=False),
    sa.Column('discovered_from_source_id', sa.UUID(), nullable=True),
    sa.Column('discovery_context', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('discovery_context_hash', sa.String(length=64), nullable=True),
    sa.Column('relevance_hint', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("discovery_method IN ('SITEMAP','CRAWL_LINK','SEARCH','JOB_BOARD','REGISTRY','HUMAN_SEED','API')", name=op.f('ck_research_source_discoveries_ck_discovery_method_vocabulary')),
    sa.ForeignKeyConstraint(['attempt_id'], ['operational_research_attempts.id'], name=op.f('fk_research_source_discoveries_attempt_id_operational_research_attempts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['discovered_from_source_id'], ['research_sources.id'], name=op.f('fk_research_source_discoveries_discovered_from_source_id_research_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], name=op.f('fk_research_source_discoveries_source_id_research_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_source_discoveries'))
    )
    op.create_index('ix_discovery_attempt', 'research_source_discoveries', ['attempt_id'], unique=False)
    op.create_index('uq_discovery_identity', 'research_source_discoveries', ['source_id', 'attempt_id', 'discovery_method', 'discovered_from_source_id', 'discovery_context_hash'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('identity_review_signal_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurrence_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','ACKNOWLEDGED','ACTIONED','DISMISSED')", name=op.f('ck_identity_review_signal_events_ck_signal_status_vocabulary')),
    sa.ForeignKeyConstraint(['occurrence_id'], ['identity_review_signal_occurrences.id'], name=op.f('fk_identity_review_signal_events_occurrence_id_identity_review_signal_occurrences'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_review_signal_events')),
    sa.UniqueConstraint('occurrence_id', 'status', 'occurred_at', name='uq_signal_event')
    )
    op.create_index('ix_signal_events_occurrence', 'identity_review_signal_events', ['occurrence_id', 'occurred_at'], unique=False)
    op.create_table('research_evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_id', sa.UUID(), nullable=False),
    sa.Column('fetch_event_id', sa.UUID(), nullable=False),
    sa.Column('artifact_derivation_id', sa.UUID(), nullable=False),
    sa.Column('body_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('locator_hash', sa.String(length=64), nullable=False),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('quote_sha256', sa.String(length=64), nullable=True),
    sa.Column('publisher_key', sa.String(length=255), nullable=False),
    sa.Column('publisher_policy_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_derivation_id', 'body_id'], ['research_artifact_derivations.id', 'research_artifact_derivations.body_id'], name='fk_evidence_derivation_same_body'),
    sa.ForeignKeyConstraint(['artifact_derivation_id'], ['research_artifact_derivations.id'], name=op.f('fk_research_evidence_items_artifact_derivation_id_research_artifact_derivations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['body_id'], ['research_artifact_bodies.id'], name=op.f('fk_research_evidence_items_body_id_research_artifact_bodies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['extraction_id', 'body_id'], ['research_extractions.id', 'research_extractions.body_id'], name='fk_evidence_extraction_same_body'),
    sa.ForeignKeyConstraint(['extraction_id'], ['research_extractions.id'], name=op.f('fk_research_evidence_items_extraction_id_research_extractions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fetch_event_id', 'body_id'], ['research_fetch_events.id', 'research_fetch_events.body_id'], name='fk_evidence_fetch_same_body'),
    sa.ForeignKeyConstraint(['fetch_event_id'], ['research_fetch_events.id'], name=op.f('fk_research_evidence_items_fetch_event_id_research_fetch_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], name=op.f('fk_research_evidence_items_source_id_research_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_evidence_items')),
    sa.UniqueConstraint('extraction_id', 'fetch_event_id', 'artifact_derivation_id', 'locator_hash', name='uq_evidence_item_identity')
    )
    op.create_index('ix_evidence_fetch', 'research_evidence_items', ['fetch_event_id'], unique=False)
    op.create_index('ix_evidence_lineage', 'research_evidence_items', ['source_id', 'artifact_derivation_id'], unique=False)
    op.create_table('research_source_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_source_id', sa.UUID(), nullable=False),
    sa.Column('to_source_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=24), nullable=False),
    sa.Column('edge_origin', sa.String(length=16), nullable=False),
    sa.Column('observed_by_fetch_event_id', sa.UUID(), nullable=True),
    sa.Column('corroborating_fetch_event_id', sa.UUID(), nullable=True),
    sa.Column('asserted_by', sa.String(length=128), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(edge_origin = 'FETCH_OBSERVED' AND observed_by_fetch_event_id IS NOT NULL    AND corroborating_fetch_event_id IS NULL) OR (edge_origin = 'DERIVED' AND observed_by_fetch_event_id IS NOT NULL    AND corroborating_fetch_event_id IS NOT NULL) OR (edge_origin = 'HUMAN_ASSERTED' AND asserted_by IS NOT NULL    AND rationale IS NOT NULL)", name=op.f('ck_research_source_edges_ck_edge_origin_requires_evidence')),
    sa.CheckConstraint("edge_origin IN ('FETCH_OBSERVED','DERIVED','HUMAN_ASSERTED')", name=op.f('ck_research_source_edges_ck_edge_origin_vocabulary')),
    sa.CheckConstraint("relation_type <> 'MIRROR_CANDIDATE' OR edge_origin <> 'FETCH_OBSERVED'", name=op.f('ck_research_source_edges_ck_mirror_is_derived')),
    sa.CheckConstraint("relation_type IN ('REDIRECTS_TO','DECLARES_CANONICAL','LANGUAGE_VARIANT_OF','MIRROR_CANDIDATE')", name=op.f('ck_research_source_edges_ck_edge_relation_vocabulary')),
    sa.ForeignKeyConstraint(['corroborating_fetch_event_id'], ['research_fetch_events.id'], name=op.f('fk_research_source_edges_corroborating_fetch_event_id_research_fetch_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_source_id'], ['research_sources.id'], name=op.f('fk_research_source_edges_from_source_id_research_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['observed_by_fetch_event_id'], ['research_fetch_events.id'], name=op.f('fk_research_source_edges_observed_by_fetch_event_id_research_fetch_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_source_id'], ['research_sources.id'], name=op.f('fk_research_source_edges_to_source_id_research_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_source_edges'))
    )
    op.create_index('ix_edges_to_source', 'research_source_edges', ['to_source_id'], unique=False)
    op.create_index('uq_source_edge', 'research_source_edges', ['from_source_id', 'to_source_id', 'relation_type', 'observed_by_fetch_event_id'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('identity_review_signal_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_occurrence_id', sa.UUID(), nullable=False),
    sa.Column('evidence_item_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['research_evidence_items.id'], name=op.f('fk_identity_review_signal_evidence_evidence_item_id_research_evidence_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['signal_occurrence_id'], ['identity_review_signal_occurrences.id'], name=op.f('fk_identity_review_signal_evidence_signal_occurrence_id_identity_review_signal_occurrences'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_review_signal_evidence')),
    sa.UniqueConstraint('signal_occurrence_id', 'evidence_item_id', name='uq_signal_evidence')
    )
    op.create_table('claim_evidence_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('evidence_item_id', sa.UUID(), nullable=False),
    sa.Column('support_kind', sa.String(length=24), nullable=False),
    sa.Column('source_class', sa.String(length=32), nullable=False),
    sa.Column('trust_policy_version', sa.String(length=16), nullable=False),
    sa.Column('trust_tier', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_class IN ('COMPANY_OWN_SITE','GOVERNMENT_REGISTRY','JOB_BOARD','THIRD_PARTY_DIRECTORY','NEWS_MEDIA','VENDOR_SITE','UNKNOWN')", name=op.f('ck_claim_evidence_links_ck_source_class_vocabulary')),
    sa.CheckConstraint("support_kind IN ('DIRECT_STATEMENT','DERIVED','CORROBORATING')", name=op.f('ck_claim_evidence_links_ck_support_kind_vocabulary')),
    sa.CheckConstraint('trust_tier >= 0 AND trust_tier <= 1', name=op.f('ck_claim_evidence_links_ck_trust_tier_range')),
    sa.ForeignKeyConstraint(['claim_id'], ['company_claims.id'], name=op.f('fk_claim_evidence_links_claim_id_company_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['research_evidence_items.id'], name=op.f('fk_claim_evidence_links_evidence_item_id_research_evidence_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_evidence_links')),
    sa.UniqueConstraint('claim_id', 'evidence_item_id', name='uq_claim_evidence')
    )
    op.create_index('ix_claim_evidence_item', 'claim_evidence_links', ['evidence_item_id'], unique=False)
    op.create_table('operational_research_gap_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gap_id', sa.UUID(), nullable=False),
    sa.Column('event_kind', sa.String(length=16), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('fetch_event_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by_claim_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("event_kind IN ('RAISED','ATTEMPTED','RESOLVED','ABANDONED')", name=op.f('ck_operational_research_gap_events_ck_gap_event_vocabulary')),
    sa.ForeignKeyConstraint(['attempt_id'], ['operational_research_attempts.id'], name=op.f('fk_operational_research_gap_events_attempt_id_operational_research_attempts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fetch_event_id'], ['research_fetch_events.id'], name=op.f('fk_operational_research_gap_events_fetch_event_id_research_fetch_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gap_id'], ['operational_research_gaps.id'], name=op.f('fk_operational_research_gap_events_gap_id_operational_research_gaps'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_claim_id'], ['company_claims.id'], name=op.f('fk_operational_research_gap_events_resolved_by_claim_id_company_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], name=op.f('fk_operational_research_gap_events_source_id_research_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_research_gap_events'))
    )
    op.create_index('ix_gap_events_gap_time', 'operational_research_gap_events', ['gap_id', 'occurred_at'], unique=False)
    op.create_index('uq_gap_event_identity', 'operational_research_gap_events', ['gap_id', 'event_kind', 'attempt_id', 'source_id', 'fetch_event_id'], unique=True, postgresql_nulls_not_distinct=True)

    # ------------------------------------------------------------------
    # Invariants autogenerate cannot express. Generated from
    # boro_gtm.research.enums, so the Python vocabulary and the SQL that
    # enforces it cannot drift apart.
    # ------------------------------------------------------------------

    # Append-only evidence: reuse M0's rejection trigger (ADR-018).
    for table in ['research_source_discoveries', 'research_source_edges', 'research_fetch_events', 'research_body_classifications', 'research_artifact_derivations', 'research_attempt_extractions', 'research_evidence_items', 'claim_evidence_links', 'operational_research_gap_events', 'identity_review_signal_evidence', 'identity_review_signal_events', 'operational_research_runs', 'research_sources', 'research_artifacts', 'operational_research_gaps', 'identity_review_signals']:
        op.execute(
            f"""
            CREATE TRIGGER {table}_no_update
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION gtm_reject_update();
            """
        )

    # One-way prune: a retained payload may become NULL exactly once, together
    # with its retention flag. Every other UPDATE is rejected (M3-ADR-008).
    op.execute("""
        CREATE OR REPLACE FUNCTION gtm_m3_one_way_prune() RETURNS trigger AS $$
        DECLARE
            payload_col text := TG_ARGV[0];
            state_col   text := TG_ARGV[1];
            old_payload text;
            new_payload text;
            old_state   text;
            new_state   text;
        BEGIN
            EXECUTE format('SELECT ($1).%I IS NULL', payload_col)
                INTO old_payload USING OLD;
            EXECUTE format('SELECT ($1).%I IS NULL', payload_col)
                INTO new_payload USING NEW;
            EXECUTE format('SELECT ($1).%I', state_col) INTO old_state USING OLD;
            EXECUTE format('SELECT ($1).%I', state_col) INTO new_state USING NEW;

            IF old_payload = 'false' AND new_payload = 'true'
               AND old_state = 'RETAINED' AND new_state = 'PRUNED' THEN
                RETURN NEW;
            END IF;
            RAISE EXCEPTION
                'append-only: % permits only a one-way prune of %',
                TG_TABLE_NAME, payload_col;
        END;
        $$ LANGUAGE plpgsql;
    """)
    for table, payload, state in [('research_artifact_bodies', 'raw_body', 'body_retention'), ('research_text_derivations', 'extracted_text', 'text_retention')]:
        op.execute(
            f"""
            CREATE TRIGGER {table}_one_way_prune
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION
                gtm_m3_one_way_prune('{payload}', '{state}');
            """
        )
    op.execute("""
        CREATE TRIGGER research_extractions_one_way_prune
        BEFORE UPDATE ON research_extractions
        FOR EACH ROW EXECUTE FUNCTION gtm_reject_update();
    """)

    # Attempt lifecycle: only legal transitions, terminal states final, and
    # seeds frozen once execution begins (M3-ADR-019, M3-ADR-036).
    op.execute("""
        CREATE OR REPLACE FUNCTION gtm_m3_attempt_transition() RETURNS trigger AS $$
        BEGIN
            IF NEW.status <> OLD.status THEN
                IF NOT (CASE OLD.status
            WHEN 'ASSERTING' THEN NEW.status IN ('COMPLETED','FAILED','PARTIAL')
            WHEN 'COMPLETED' THEN FALSE
            WHEN 'DISCOVERING' THEN NEW.status IN ('FAILED','FETCHING','PARTIAL')
            WHEN 'EXTRACTING' THEN NEW.status IN ('ASSERTING','FAILED','PARTIAL')
            WHEN 'FAILED' THEN FALSE
            WHEN 'FETCHING' THEN NEW.status IN ('EXTRACTING','FAILED','PARTIAL')
            WHEN 'PARTIAL' THEN FALSE
            WHEN 'PENDING' THEN NEW.status IN ('DISCOVERING','FAILED','PARTIAL')
            ELSE FALSE END) THEN
                    RAISE EXCEPTION
                        'illegal attempt transition % -> %', OLD.status, NEW.status;
                END IF;
            END IF;
            IF OLD.status <> 'PENDING'
               AND NEW.attempt_seed_inputs IS DISTINCT FROM OLD.attempt_seed_inputs THEN
                RAISE EXCEPTION
                    'attempt_seed_inputs are frozen once execution begins';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER operational_research_attempts_transition
        BEFORE UPDATE ON operational_research_attempts
        FOR EACH ROW EXECUTE FUNCTION gtm_m3_attempt_transition();
    """)

    # Gap and signal event logs: a terminal event admits no successor.
    op.execute("""
        CREATE OR REPLACE FUNCTION gtm_m3_gap_event_transition() RETURNS trigger AS $$
        DECLARE latest text;
        BEGIN
            SELECT event_kind INTO latest
            FROM operational_research_gap_events
            WHERE gap_id = NEW.gap_id
            ORDER BY occurred_at DESC, id DESC LIMIT 1;
            IF latest IS NULL THEN
                IF NEW.event_kind <> 'RAISED' THEN
                    RAISE EXCEPTION 'a gap must open with RAISED, got %', NEW.event_kind;
                END IF;
                RETURN NEW;
            END IF;
            IF NOT (CASE latest
            WHEN 'ABANDONED' THEN FALSE
            WHEN 'ATTEMPTED' THEN NEW.event_kind IN ('ABANDONED','ATTEMPTED','RESOLVED')
            WHEN 'RAISED' THEN NEW.event_kind IN ('ABANDONED','ATTEMPTED','RESOLVED')
            WHEN 'RESOLVED' THEN FALSE
            ELSE FALSE END) THEN
                RAISE EXCEPTION 'illegal gap transition % -> %', latest, NEW.event_kind;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER operational_research_gap_events_transition
        BEFORE INSERT ON operational_research_gap_events
        FOR EACH ROW EXECUTE FUNCTION gtm_m3_gap_event_transition();
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION gtm_m3_signal_event_transition() RETURNS trigger AS $$
        DECLARE latest text;
        BEGIN
            SELECT status INTO latest
            FROM identity_review_signal_events
            WHERE occurrence_id = NEW.occurrence_id
            ORDER BY occurred_at DESC, id DESC LIMIT 1;
            IF latest IS NULL THEN
                IF NEW.status <> 'OPEN' THEN
                    RAISE EXCEPTION 'a review occurrence must open with OPEN, got %',
                        NEW.status;
                END IF;
            ELSIF NOT (CASE latest
            WHEN 'ACKNOWLEDGED' THEN NEW.status IN ('ACTIONED','DISMISSED')
            WHEN 'ACTIONED' THEN FALSE
            WHEN 'DISMISSED' THEN FALSE
            WHEN 'OPEN' THEN NEW.status IN ('ACKNOWLEDGED','DISMISSED')
            ELSE FALSE END) THEN
                RAISE EXCEPTION 'illegal signal transition % -> %', latest, NEW.status;
            END IF;
            -- Keep is_open in step so the partial unique index can hold at most
            -- one live episode per concern without reading the event log.
            UPDATE identity_review_signal_occurrences
               SET is_open = (NEW.status NOT IN ('ACTIONED','DISMISSED'))
             WHERE id = NEW.occurrence_id;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER identity_review_signal_events_transition
        BEFORE INSERT ON identity_review_signal_events
        FOR EACH ROW EXECUTE FUNCTION gtm_m3_signal_event_transition();
    """)
    # The occurrence row is otherwise immutable; only is_open may move.
    op.execute("""
        CREATE OR REPLACE FUNCTION gtm_m3_occurrence_guard() RETURNS trigger AS $$
        BEGIN
            IF NEW.signal_id IS DISTINCT FROM OLD.signal_id
               OR NEW.occurrence_number IS DISTINCT FROM OLD.occurrence_number
               OR NEW.raised_by_attempt_id IS DISTINCT FROM OLD.raised_by_attempt_id
               OR NEW.supersedes_occurrence_id IS DISTINCT FROM OLD.supersedes_occurrence_id
               OR NEW.raised_at IS DISTINCT FROM OLD.raised_at THEN
                RAISE EXCEPTION
                    'append-only: only is_open may change on a review occurrence';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER identity_review_signal_occurrences_guard
        BEFORE UPDATE ON identity_review_signal_occurrences
        FOR EACH ROW EXECUTE FUNCTION gtm_m3_occurrence_guard();
    """)

    # ------------------------------------------------------------------
    # Additive changes to M2-owned objects (design §5). No existing column,
    # CHECK or index is altered.
    # ------------------------------------------------------------------
    op.add_column(
        "attribute_definitions",
        sa.Column("owner_milestone", sa.String(length=8), nullable=True),
    )
    op.execute("UPDATE attribute_definitions SET owner_milestone = 'M2'")

    op.add_column(
        "company_claims",
        sa.Column("assertion_fingerprint", sa.String(length=64), nullable=True),
    )
    op.execute("""
        CREATE UNIQUE INDEX uq_claim_assertion_fingerprint
        ON company_claims (assertion_fingerprint)
        WHERE assertion_fingerprint IS NOT NULL;
    """)

    # An M3-owned claim with no evidence is unrepresentable, not merely
    # discouraged (M3-ADR-003). Deferred, because the claim and its links are
    # written in one transaction and the order must not matter.
    op.execute("""
        CREATE OR REPLACE FUNCTION gtm_m3_claim_requires_evidence() RETURNS trigger AS $$
        DECLARE owner text;
        BEGIN
            SELECT owner_milestone INTO owner
            FROM attribute_definitions
            WHERE attribute_key = NEW.attribute_key
              AND registry_version = NEW.attribute_registry_version;
            IF owner IS DISTINCT FROM 'M3' THEN
                RETURN NEW;
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM claim_evidence_links WHERE claim_id = NEW.id
            ) THEN
                RAISE EXCEPTION
                    'an M3 claim requires at least one claim_evidence_links row';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE CONSTRAINT TRIGGER company_claims_m3_requires_evidence
        AFTER INSERT ON company_claims
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION gtm_m3_claim_requires_evidence();
    """)

    # ------------------------------------------------------------------
    # Views. Everything time-varying or event-derived lives here.
    # ------------------------------------------------------------------
    op.execute("""
        CREATE VIEW current_operational_research_gaps AS
        SELECT g.*,
               s.current_status,
               s.attempt_count,
               s.attempted_source_count,
               s.last_attempt_at,
               s.resolved_by_claim_id
        FROM operational_research_gaps g
        LEFT JOIN LATERAL (
            SELECT
              (SELECT event_kind FROM operational_research_gap_events e
                WHERE e.gap_id = g.id ORDER BY occurred_at DESC, id DESC LIMIT 1)
                AS current_status,
              count(*) FILTER (WHERE e2.event_kind = 'ATTEMPTED') AS attempt_count,
              count(DISTINCT e2.source_id) FILTER (WHERE e2.event_kind = 'ATTEMPTED')
                AS attempted_source_count,
              max(e2.occurred_at) FILTER (WHERE e2.event_kind = 'ATTEMPTED')
                AS last_attempt_at,
              (SELECT resolved_by_claim_id FROM operational_research_gap_events e3
                WHERE e3.gap_id = g.id AND e3.event_kind = 'RESOLVED'
                ORDER BY occurred_at DESC, id DESC LIMIT 1) AS resolved_by_claim_id
            FROM operational_research_gap_events e2 WHERE e2.gap_id = g.id
        ) s ON TRUE;
    """)
    op.execute("""
        CREATE VIEW current_identity_review_occurrences AS
        SELECT o.*,
               (SELECT status FROM identity_review_signal_events e
                 WHERE e.occurrence_id = o.id
                 ORDER BY occurred_at DESC, id DESC LIMIT 1) AS current_status
        FROM identity_review_signal_occurrences o;
    """)
    op.execute("""
        CREATE VIEW research_source_retrieval_history AS
        SELECT f.source_id, f.id AS fetch_event_id, f.retrieved_at,
               f.fetch_outcome, f.http_status, f.body_id, f.attempt_id
        FROM research_fetch_events f
        ORDER BY f.source_id, f.retrieved_at DESC;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:

    op.execute("DROP VIEW IF EXISTS research_source_retrieval_history")
    op.execute("DROP VIEW IF EXISTS current_identity_review_occurrences")
    op.execute("DROP VIEW IF EXISTS current_operational_research_gaps")
    op.execute("DROP TRIGGER IF EXISTS company_claims_m3_requires_evidence ON company_claims")
    op.execute("DROP FUNCTION IF EXISTS gtm_m3_claim_requires_evidence()")
    op.execute("DROP INDEX IF EXISTS uq_claim_assertion_fingerprint")
    op.drop_column("company_claims", "assertion_fingerprint")
    op.drop_column("attribute_definitions", "owner_milestone")
    for fn in (
        "gtm_m3_occurrence_guard", "gtm_m3_signal_event_transition",
        "gtm_m3_gap_event_transition", "gtm_m3_attempt_transition",
        "gtm_m3_one_way_prune",
    ):
        op.execute(f"DROP FUNCTION IF EXISTS {fn}() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_gap_event_identity', table_name='operational_research_gap_events', postgresql_nulls_not_distinct=True)
    op.drop_index('ix_gap_events_gap_time', table_name='operational_research_gap_events')
    op.drop_table('operational_research_gap_events')
    op.drop_index('ix_claim_evidence_item', table_name='claim_evidence_links')
    op.drop_table('claim_evidence_links')
    op.drop_table('identity_review_signal_evidence')
    op.drop_index('uq_source_edge', table_name='research_source_edges', postgresql_nulls_not_distinct=True)
    op.drop_index('ix_edges_to_source', table_name='research_source_edges')
    op.drop_table('research_source_edges')
    op.drop_index('ix_evidence_lineage', table_name='research_evidence_items')
    op.drop_index('ix_evidence_fetch', table_name='research_evidence_items')
    op.drop_table('research_evidence_items')
    op.drop_index('ix_signal_events_occurrence', table_name='identity_review_signal_events')
    op.drop_table('identity_review_signal_events')
    op.drop_index('uq_discovery_identity', table_name='research_source_discoveries', postgresql_nulls_not_distinct=True)
    op.drop_index('ix_discovery_attempt', table_name='research_source_discoveries')
    op.drop_table('research_source_discoveries')
    op.drop_index('ix_fetch_source_time', table_name='research_fetch_events')
    op.drop_index('ix_fetch_body', table_name='research_fetch_events')
    op.drop_index('ix_fetch_attempt', table_name='research_fetch_events')
    op.drop_table('research_fetch_events')
    op.drop_index('ix_attempt_extraction_extraction', table_name='research_attempt_extractions')
    op.drop_table('research_attempt_extractions')
    op.drop_index('uq_occurrence_open', table_name='identity_review_signal_occurrences', postgresql_where='is_open')
    op.drop_index('ix_occurrence_attempt', table_name='identity_review_signal_occurrences')
    op.drop_table('identity_review_signal_occurrences')
    op.drop_index('uq_extraction_contract', table_name='research_extractions', postgresql_nulls_not_distinct=True)
    op.drop_table('research_extractions')
    op.drop_table('operational_research_plan_profiles')
    op.drop_index('ix_gaps_company_kind', table_name='operational_research_gaps')
    op.drop_table('operational_research_gaps')
    op.drop_index('uq_attempt_live', table_name='operational_research_attempts', postgresql_where="status NOT IN ('COMPLETED','PARTIAL','FAILED')")
    op.drop_index('ix_attempts_status', table_name='operational_research_attempts')
    op.drop_table('operational_research_attempts')
    op.drop_table('research_text_derivations')
    op.drop_table('research_body_classifications')
    op.drop_index('ix_derivations_artifact', table_name='research_artifact_derivations')
    op.drop_table('research_artifact_derivations')
    op.drop_index('ix_research_runs_company', table_name='operational_research_runs')
    op.drop_table('operational_research_runs')
    op.drop_table('operational_research_profiles')
    op.drop_index('ix_signals_company_kind', table_name='identity_review_signals')
    op.drop_table('identity_review_signals')
    op.drop_index('ix_sources_registrable_domain', table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_table('research_artifacts')
    op.drop_index('ix_bodies_retained', table_name='research_artifact_bodies')
    op.drop_table('research_artifact_bodies')
    # ### end Alembic commands ###
